### ISSUE TITLE
Decode square brackets

### ISSUE THREAD

**Issue by stevelacey** [spatie/laravel-json-api-paginate#23]
I don't know if this annoys anyone else but the encoded square brackets in the `links` block was bothering me, and it's hard to remove given it comes from `http_build_query` in Laravel's AbstractPaginator – you'd have to swap out core paginator or patch it to remove it

I am already recoding my json in a few places for reasons – and doing it again is no big deal to me, so I wrote this middleware to decode square brackets within the `links` block whenever they're found  
(e.g. when `page[number]` and `page[size]` are present)

```php
<?php

namespace App\Http\Middleware;

use Closure;

class DecodeLinkBrackets
{
    /**
     * Handle an incoming request.
     *
     * @param  Request  $request
     * @param  Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        if ($response->headers->get('Content-Type') == 'application/json') {
            $json = json_decode($response->getContent());

            if (isset($json->links)) {
                $json->links = (object) array_map(
                    function ($url) {
                        if (is_string($url)) {
                            return str_replace('%5B', '[', str_replace('%5D', ']', $url));
                        }

                        return $url;
                    },
                    (array) $json->links
                );
            }

            $response->setContent(json_encode($json));
        }

        return $response;
    }
}
```

@freekmurze if this is at all desirable in this library I can submit a PR - but I imagine it is beyond scope – just posting here for anyone looking for a solution to this

**Comment by brentkozjak** [comment]
I just wanted to say thanks for this.  My OCD kicked in and the link character encoding annoyed the hell out of me.  I also noticed that Laravel encodes the commas by default, so I made a new class based on your code called `DecodeLinkCharacters` and modified the returned string to:

`return str_replace(['%5B', '%5D', '%2C'], ['[', ']', ','], $url);`

That way links would maintain commas in the case of multiple includes, etc:

`GET /posts?include=comments,attachments`

If there's a cleaner/safer/more efficient way to do this, I'd love to know.  Cheers!

**Comment by stevelacey** [comment]
@brentkozjak I just started using spatie/laravel-query-builder too – so yeah, this was imminently going to annoy me too – I've updated my code and the example above – thanks! 😀👌

**Comment by gcw07** [comment]
I know this is a little old, but I had to do it in a different way to get it to work and thought it might help someone else. When your using Eloquent API Resources, it nests the links deep inside the returned data so you can't just do $json->links unfortunately. So I mixed your method with overriding the LengthAwarePaginator class. In your AppServiceProvider.php file, add this to the register() method:

```php
$this->app->bind(LengthAwarePaginator::class, function ($app, $values) {
            return new class(...array_values($values)) extends LengthAwarePaginator {
                public function toArray()
                {
                    $pages = [
                        'current_page' => $this->currentPage(),
                        'data' => $this->items->toArray(),
                        'first_page_url' => $this->url(1),
                        'from' => $this->firstItem(),
                        'last_page' => $this->lastPage(),
                        'last_page_url' => $this->url($this->lastPage()),
                        'next_page_url' => $this->nextPageUrl(),
                        'path' => $this->path(),
                        'per_page' => $this->perPage(),
                        'prev_page_url' => $this->previousPageUrl(),
                        'to' => $this->lastItem(),
                        'total' => $this->total(),
                    ];

                    return array_map(
                        function ($url) {
                            if (is_string($url)) {
                                return str_replace(['%5B', '%5D', '%2C'], ['[', ']', ','], $url);
                            }

                            return $url;
                        },
                        $pages
                    );
                }
            };
});
```
I'm basically just overriding the toArray method and running the urls through the same array_map stevelacy was using.

**Comment by activemonkeys** [comment]
Thanks for posting this gcw07. This is exactly what I was looking for.
