### ISSUE TITLE
Package not working in Lumen

### ISSUE THREAD

**Issue by J5Dev** [spatie/laravel-json-api-paginate#25]
I'm not sure if this is intentional, as . it is not specified, but the package does not seem to work in Lumen 5.6

Firstly, it seems the service provider autodiscovery is not working, as whet attempting Model::jsonPaginate() I receive a BadMethodCallException.

`Method Illuminate\Database\Query\Builder::jsonPaginate does not exist.`

When manually adding the service provider to bootstrap/app.php, I receive the following error...

`Call to undefined function Spatie\JsonApiPaginate\request()`

Is this an actual error, or is the package not usable within Lumen?

Thanks

**Comment by J5Dev** [comment]
OK, so I 'think' I have got to the bottom of this, and confirmed it does not work within lumen. I have it working.

In order to get it to work, a number of things are needed...

1. Within the service provider, the use of `request()` needs to be updated to `app('request')`

2. The service provider has to be manually added to the bootstrap/app.php file

    `$app->register(Spatie\JsonApiPaginate\JsonApiPaginateServiceProvider::class);`

3. The configs must be manually loaded

Copy the config into the config directory (creating it if not done already), and then add the following to bootstrap/app.php

```
$app->withFacades();
$app->withEloquent();
$app->configure('json-api-paginate'); <--- This is the line to add
```

Downside to this is it requires editing the vendor file, so its a no goer for me at the mo other than testing... If nobody beats me to it I will look and see what I can do to make it Lumen compliant sometime during the week.

**Comment by freekmurze** [comment]
We don't use Lumen for our projects (and I personally think that Lumen is going away at some point in the future). That's why we don't support it in our packages.

If you need Lumen compatibility, fork our code and maintain your own Lumen compatible copy.
