### ISSUE TITLE
I don't want to use the solid bracket in query

### ISSUE THREAD

**Issue by superern** [spatie/laravel-json-api-paginate#26]
Hi ,

What if I don't want to use a solid bracket in page number?
like so:
base_url/users?page=2

**Comment by brentkozjak** [comment]
That is the behaviour of the default Laravel paginator.  Since you want that, why use this package at all?  This package simply conforms the pagination URL parameters to JSON API standards.

**Comment by sebastiandedeyne** [comment]
This package was made to conform to the JSON API spec. We're not going to add any options to derive from the standard.
