### ISSUE TITLE
[Question] About API Resources

### ISSUE THREAD

**Issue by kennyhorna** [spatie/laravel-json-api-paginate#29]
Hello, nice package!

I have a question, can I use this alongside [API Resources](https://laravel.com/docs/5.7/eloquent-resources)? 

I mean, sometimes you want to customize the response data to be returned to, in my case, in an API response. Could this be used somehow with [API Resources](https://laravel.com/docs/5.7/eloquent-resources)?

Thanks in advance.

Btw, happy holidays to you guys!

**Comment by freekmurze** [comment]
Yeah, sure you can use this together 👍

**Comment by kennyhorna** [comment]
@freekmurze nice to hear that. My question but a little bit more of "how". Could you provide a simple example? 
Regards from Peru.

**Comment by freekmurze** [comment]
API resources determine how a resource is transformed. This package helps with building the query that selects models out of the database. They work independently from each other.

Use our package to select models. Pass those models to an API resource to transform them.
