### ISSUE TITLE
Passing maxResults to jsonPaginate not working as expected

### ISSUE THREAD

**Issue by bessonette** [spatie/laravel-json-api-paginate#33]
First, this is a great package that we've used and seen used many times. We just ran into an issue with passing $maxResults to jsonPaginate(). The initial reading of the README seems to indicate that this value will set the page size. However, that appears to only be the case if the $maxResults value is smaller than the default page size. 

In our case, we have a default page size of 25, but had some instances where we wanted 50 records returned. Using jsonPaginate(50) continued to return 25 records. After digging into the code a little we decided to use jsonPaginate(50, 50) to achieve the desired result. This definitely works, but it was slightly confusing since our dev expected the value passed in to set the page size. We're happy to update the README and create a PR if that's helpful. 

https://github.com/spatie/laravel-json-api-paginate/blob/ecec3cd60c45dd0fd6671ac1ea4d3bb9fbe7b674/src/JsonApiPaginateServiceProvider.php#L37

**Comment by freekmurze** [comment]
Feel free to pupdate the readme to make it more clear 👍
