### ISSUE TITLE
Is there a way to use this with laravel-fractal

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/laravel-json-api-paginate#34]
I am trying to limit the number of fields retrieved when using `jsonPaginate` and pass it through a transformer may be. Is there a way to do this or use it with `laravel-fractal`? Or is there a way to specify what columns it should retrieve?

**Comment by freekmurze** [comment]
This package only limits the results, not the columns. You can limit the columns by doing

```
YourModel::query()->select($columnNames)->jsonPaginate()
```

**Comment by abishekrsrikaanth** [comment]
Actually the issue that I am having is that I want to transform some data before I return a response back to the UI, for example transforming the `id` column to an encrypted value instead of the incrementing value. Can you suggest if there is a way to do this. I have a mutator on my model that does that, but defining the `id` column. Sending the response based on the select column kind of defeats the purpose of encoding the column.

**Comment by freekmurze** [comment]
Take a look at Eloquent resources (https://laravel.com/docs/master/eloquent-resources) or Fractal to transform data (https://github.com/spatie/laravel-fractal).
