### ISSUE TITLE
JsonPagination is private.

### ISSUE THREAD

**Issue by WayneBrummer** [spatie/laravel-json-api-paginate#37]
Hello,
I have come across a issue in regards to using php 7.3 along with Query Builder and JSON Pagination.

The Query
```
return QueryBuilder::for(User::class)->jsonPaginate();
```

The issue I am pulling from phpstan error check.
```
Call to private method jsonPaginate() of parent class Illuminate\Database\Eloquent\Builder.
```

**Comment by freekmurze** [comment]
phpstan probably can't detect that `jsonPaginate` was added via a macro.
