### ISSUE TITLE
Limit builder method does not limit the results.

### ISSUE THREAD

**Issue by tiapossoftware** [spatie/laravel-json-api-paginate#40]
If I do the following it works fine:
`Submission::select(...)->orderBy(...)->jsonPaginate();`

But if I try and limit the rows, I still get them all:
`Submission::select(...)->orderBy(...)->limit(1)->jsonPaginate();`

Am I doing something wrong?

**Comment by guetteman** [comment]
Hi, I think that you shouldn't use `limit()` with jsonPaginate. Remember that you already have the query param `page[size]=1`.

**Comment by tiapossoftware** [comment]
The limit() call is used in my select just to get the most recent row, using the `page[size]=1` param will still look to the requesting client that there are more results.
Is there another way to just get s single row?

**Comment by tiapossoftware** [comment]
You cannot use limit() with this as it needs it to paginate the results, my mistake.
