### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by gamevnlc** [spatie/laravel-json-api-paginate#44]
I try to publish  the config file when I run this command 
`php artisan vendor:publish --provider="Spatie\JsonApiPaginate\JsonApiPaginateServiceProvider" --tag="config"
`
I got this error:` Unable to locate publishable resources.`. Is there anyone know how to fix

**Comment by freekmurze** [comment]
Cannot reproduce this. Make sure you installed the package correctly.
