### ISSUE TITLE
API pagination url

### ISSUE THREAD

**Issue by salvatorelapi** [spatie/laravel-json-api-paginate#9]
Hi, i'm using your class,
but i have strange error, first time that i get next url by jsonPaginate i get this
https://example.com/api/v1/users/list?page[number]=2
when i run it pagination not work, i see alwais same data, but in this request i get new next url:
https://example.com/api/v1/users/list?\page[number]=2&page[number]=2
and this work fine.
If page[number] is first parameter not work, after first work.
Can you help me ?

**Comment by freekmurze** [comment]
Could you PR a failing test?
